# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='project_name',
            field=models.CharField(default='Chrome Portal', help_text='Name of the project or feature being estimated', max_length=100),
        ),
    ]
