# Generated by Django 5.2.3 on 2025-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0003_room_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='point_system',
            field=models.CharField(choices=[('fibonacci', 'Fibonacci (1, 2, 3, 5, 8, 13, 21)'), ('modified_fibonacci', 'Modified Fibonacci (0, 1/2, 1, 2, 3, 5, 8, 13, 20, 40, 100)'), ('powers_of_2', 'Powers of 2 (1, 2, 4, 8, 16, 32, 64)'), ('t_shirt', 'T-Shirt Sizes (XS, S, M, L, XL, XXL)')], default='fibonacci', help_text='Point system used for estimation', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='project_name',
            field=models.CharField(default='Cyber Infinity 3000', help_text='Name of the project or feature being estimated', max_length=100),
        ),
    ]
