# Generated by Django 5.2.3 on 2025-06-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0005_room_allow_skip_room_auto_reveal_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_timer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='last_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_admin_room', to='planning_poker.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='enable_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='project_name',
            field=models.CharField(default='Neural Node', help_text='Name of the project or feature being estimated', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='timer_duration',
            field=models.IntegerField(default=300),
        ),
    ]
