# Generated by Django 5.2.3 on 2025-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0006_room_auto_closed_room_is_timer_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='project_name',
            field=models.CharField(default='Crystal Eclipse', help_text='Name of the project or feature being estimated', max_length=100),
        ),
    ]
