# Generated by Django 5.2.3 on 2025-10-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0007_alter_room_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or feature being estimated', max_length=100),
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
